version: '3'

services:
  mongo:
    image: mongo:3.2
    container_name: mongo-db
    hostname: mongo-db
    ports:
      - "27017:27017"

  car-polygon:
    build: .
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - "8080:8080"
    command: java -jar target/car-polygon-0.0.1-SNAPSHOT.jar
    tty: true