version: '3'

services:
  mongo:
    image: mongo:3.2
    container_name: mongo-db
    hostname: mongo-db
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"

  car-polygon:
    build: .
    depends_on:
      - mongo
      - redis
    links:
      - mongo
      - redis
    ports:
      - "8080:8080"
    command: java -jar target/car-polygon-0.0.1-SNAPSHOT.jar
    tty: true